name: HotelCombe
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9205868470016867
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1a1a1a'
    - '#c8e2f1'
    - '#676966'
    - '#fefefe'
    - '#9cb977'
  brandStrength: 0.5
  lightness: 0.7296577412635088
  saturation: 0.06277567683719099
  rhythmicContrast: 0.28478128579445183
purpose: []
