name: HotelCombe
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9205868470016867
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5
  lightness: 0.7296577412635088
  saturation: 0.06277567683719099
  rhythmicContrast: 0.28478128579445183
purpose: []
